import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./provider";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <ConfigProvider>
          <Providers>{children}</Providers>
        </ConfigProvider>
      </body>
    </html>
  );
}
